### ISSUE TITLE
Triggering KeyError

### ISSUE THREAD

**Issue by tr4ssj2** [ncvo/charity-commission-extract#2]
Opened zip file: RegPlusExtract_January_2017.zip
ERROR: Did not find extract_aoo_ref.bcp in zip file
ERROR: Did not find extract_trustee.bcp in zip file
ERROR: Did not find extract_charity_aoo.bcp in zip file
ERROR: Did not find extract_main_charity.bcp in zip file
ERROR: Did not find extract_charity.bcp in zip file
ERROR: Did not find extract_financial.bcp in zip file
ERROR: Did not find extract_remove_ref.bcp in zip file
ERROR: Did not find extract_class_ref.bcp in zip file
ERROR: Did not find extract_name.bcp in zip file
ERROR: Did not find extract_class.bcp in zip file
ERROR: Did not find extract_ar_submit.bcp in zip file
ERROR: Did not find extract_objects.bcp in zip file
ERROR: Did not find extract_partb.bcp in zip file
ERROR: Did not find extract_acct_submit.bcp in zip file
ERROR: Did not find extract_registration.bcp in zip file

**Comment by drkane** [comment]
I think the Charity Commission have changed the layout of the files - there's now a parent directory holding them. It should be possible to change the script to loop through the expected files and see if the actual filename matches the expected ones ignoring the folder it is in.

**Comment by evanodell** [comment]
As a workaround, you can also extract the files from the zip file and create a new zip file without the additional directory.

**Comment by drkane** [comment]
Fixed by 454b60d
